### ISSUE TITLE
[SUPPORT]

### ISSUE THREAD

**Issue by erayko-dev** [BerkieBb/qb-target#100]
**Problem:**
I added the script to my server, no errors. In key bindings settings it set to "L Alt" but when I hit "L Alt" nothing happens.

**Wanted Outcome:**
The "third-eye/target-eye" to appear.

(in the final image, I'm pressing "L Alt" but there is nothing)

![image](https://user-images.githubusercontent.com/76734458/157858470-df14e806-3160-47bb-880d-05e24d2452a9.png)
![image](https://user-images.githubusercontent.com/76734458/157858526-8b50c196-5e13-42e1-ab86-a0b91e45c15c.png)
![image](https://user-images.githubusercontent.com/76734458/157858567-c9b4eb56-8484-4c87-a141-db6b53e38fa9.png)
![image](https://user-images.githubusercontent.com/76734458/157858625-23b8b4bb-952e-4f13-817c-55bb30ac0c29.png)

**Comment by BerkieBb** [comment]
Nothing in F8 either? qb-core updated aswell?

**Comment by xZyloHD** [comment]
Same issue happening with me. No error in F8 or server console.

**Comment by erayko-dev** [comment]
@BerkieBb nothing in F8

**Comment by BerkieBb** [comment]
qb-core updated?

**Comment by bobanmarley** [comment]
same here and yes qb-core updated , no errors in F8 or console.

**Comment by erayko-dev** [comment]
solved :)

**Comment by BerkieBb** [comment]
What solved it?
