### ISSUE TITLE
Nothing is happening while pressing LALT

### ISSUE THREAD

**Issue by xZyloHD** [BerkieBb/qb-target#101]
**Problem:**
When i press LALT nothing appears on my screen

**Wanted Outcome:**
Would like it to show up so i can start configuring it :P

**Screenshots:**
![image](https://user-images.githubusercontent.com/49572104/157912428-3db583eb-d95d-48dc-81f6-f1006ea1c0db.png)
![image](https://user-images.githubusercontent.com/49572104/157912488-4389dadc-ff03-4da0-81f6-21796839f395.png)
![image](https://user-images.githubusercontent.com/49572104/157912549-72fa97d8-8510-4d94-938d-ac9c33c5d075.png)

**Comment by BerkieBb** [comment]
qb-core needs to be updated
