### ISSUE TITLE
[SUPPORT]

### ISSUE THREAD

**Issue by Martenius1** [BerkieBb/qb-target#102]
**Problem:**
I don't understand function part of the script, but is there like somesort of pattern that I can follow?

**Wanted Outcome:**
Just to understand what I have to put in functions part of the script.

**Current Point:**
I don't understand what to put in to the function par except like RegisterNetEvent or something I know what these do, but don't know how to use them in that part.

**Screenshots:**
![image](https://user-images.githubusercontent.com/101430409/157965032-9decf5b6-3d9e-4298-b774-7e11b29a7349.png)

**Comment by Martenius1** [comment]
Nevermind, found something.

**Comment by BerkieBb** [comment]
The code in the screenshot you provided is just for setting the default functions for standalone mode, those functions get replaced further down when using QBCore and the standalone option is off
