### ISSUE TITLE
Left alt for alternative menus.

### ISSUE THREAD

**Issue by Zotactiks** [BerkieBb/qb-target#103]
I've having an issue when spawning in your apartment, When Left alt'ing to press leave appartment mouse curser is not displaying to select it. I'm using qb-housing, qb-target and qb-menus.

**Comment by BerkieBb** [comment]
But qb-apartments doesn't use the target, neither does qb-houses yet

**Comment by Zotactiks** [comment]
It uses Qb-Menu but won't let me use the menu because of qb-target

**Comment by BerkieBb** [comment]
qb-targer uses left alt to open the eye, when the eye turns blue you press right click to open the menu

**Comment by Brad1423** [comment]
Did you manage to fix this?
