### ISSUE TITLE
Change the eye picture

### ISSUE THREAD

**Issue by KRW28** [BerkieBb/qb-target#104]
Not really an issue but is there a way to replace the current Eye Icon?

**Comment by BerkieBb** [comment]
I used the quasar styling framework for the icons, so a lot of icon frameworks can be used for the eye, the naming and which of them can be found here https://quasar.dev/vue-components/icon#naming-convention
But to change the icon, just change the `CurrentEyeIcon` and `StandardEyeIcon` variable in the app.js in the html folder in the js folder

**Comment by KRW28** [comment]
> 

Awesome, Thanks!
