### ISSUE TITLE
[BUG] Eye in other menu

### ISSUE THREAD

**Issue by KingRyuShin** [BerkieBb/qb-target#105]
**Describe the bug**
The eye is activated while in other menu (exemple the map)

**To Reproduce**
1. Go to pause menu
2. Click on LALT
4. See eye in center of map marker

**Expected behavior**
Not showing in pause menu

**Screenshots**
![image](https://user-images.githubusercontent.com/42899923/159139646-0e5ec94f-a2ca-4a50-9ab2-3257488ef89a.png)

My qb-target is up-to-date

**Comment by BerkieBb** [comment]
This should be fixed with the newest version
