### ISSUE TITLE
[BUG] involuntarily shooting after triggering a event with target

### ISSUE THREAD

**Issue by Kingsage311** [BerkieBb/qb-target#106]
**Describe the bug**
When you try to trigger an action with target and you have a gun in your hand there is a chance that you will start and keep shooting until you run out of bullets in the attached video I was not shooting my gun qb-target glitched out and made made me start dumping clips no F8 or console errors 

**To Reproduce**
1. Go to anything you can target with a gun in your hand (might have to open up a menu idk)
2. Click on any action with target 
4. Start shooting 

**Expected behavior**
For it to not make me involuntarily dump clips 

**Additional context**
https://streamable.com/4ubpix

**Comment by BerkieBb** [comment]
Please check if the newest version still does the same thing

**Comment by Kingsage311** [comment]
updated and still a bug https://streamable.com/ewvrz6

**Comment by BerkieBb** [comment]
Oh after clicking, that's literally normal because it enables the controls again after clicking, you shouldn't even target something with a gun in your hand

**Comment by Kingsage311** [comment]
There are plenty of cases where someone would have a gun in their hand and want to target something like qb-jewelry, if someone is trying to put someone into a trunk and targets it to open it, and my other cases

**Comment by Kingsage311** [comment]
This might be an issue with it opening QB-menu right afterward will do more testing and then update this issue if a solution is found

**Comment by BerkieBb** [comment]
Try with the newest version https://github.com/BerkieBb/qb-target/releases/tag/5.3.8
