### ISSUE TITLE
[SUPPORT] get player var of a targeted player

### ISSUE THREAD

**Issue by skrilax91** [BerkieBb/qb-target#108]
**Problem:**
WAnt to use a global player action

**Wanted Outcome:**
I want to trigger an event with the server id of the player targetted by the action

**Current Point:**
Actually i called the add global player function in order to add a terget action, but i don't know how to transform the Ped var into a Player var or how to recover player server Id from a Ped

**Screenshots:**
![image](https://user-images.githubusercontent.com/6585219/160252410-10e8b49b-a046-479c-9dbb-e95eca52f6d7.png)

**Comment by BerkieBb** [comment]
`GetPlayerServerId(GetPlayerIndexFromPed(ent))`
This is how you get the server id from a ped

**Comment by skrilax91** [comment]
Thanks you !!

**Comment by skrilax91** [comment]
Hi !
Sorry to reopen the issue but i have a last question about this "entity", can i try to test if i can show the target action, but i need to access qb metadata of the target, can i do this with this entity object ?

**Comment by BerkieBb** [comment]
> Hi ! Sorry to reopen the issue but i have a last question about this "entity", i try to test if i can show the target action, but i need to access qb PlayerData of the target, can i do this with this entity object ?

You can't access another players playerdata from the client, you'd have to send the server id of the targeted players' server id to a callback which gets the playerdata and sends it back to the client

**Comment by skrilax91** [comment]
Okay I understand, so if I want do use another player data the best idea can be to export the target action from server-side?

**Comment by skrilax91** [comment]
Okay I understand, so to explain you what I'm trying to do, I want to add on all player the possibility for cops to handcuff, but, for some reason the function for handcuff and un handcuff are not the same. So I need to verify if the player is handcuffed in order to show the right target action, and this information is stored in the player Metadata variable.
The only one method I know for retrieve server response from client is a trigger server on a function that trigger back a client Event, but I can't do this in the canInteract variable right?
So how can I do this?

**Comment by BerkieBb** [comment]
>The only one method I know for retrieve server response from client is a trigger server on a function that trigger back a client Event, but I can't do this in the canInteract variable right?

Yes you can, it's called a callback, qb-core has that

**Comment by skrilax91** [comment]
Thanks, i maked callback like the client hasItem function of qb-core, it's work, i met an issue i think but i will describe it in an other issue
