### ISSUE TITLE
Can props be added like the ped model?

### ISSUE THREAD

**Issue by watchakorn-18k** [BerkieBb/qb-target#109]
Can props be added like the ped model?

**Comment by BerkieBb** [comment]
What do you mean?

**Comment by watchakorn-18k** [comment]
I mean can I spawn these objects?
![image](https://user-images.githubusercontent.com/74919942/160399670-cef31fd7-cd98-4623-9586-c5090042419e.png)

using qb-target

**Comment by BerkieBb** [comment]
You can't, only peds can be spawned using qb-target
