### ISSUE TITLE
[BUG] Citizen.Await()

### ISSUE THREAD

**Issue by skrilax91** [BerkieBb/qb-target#110]
**Describe the bug**
Make two Citizen.Await in two options in export brok this export

```lua
exports['qb-target']:AddGlobalPlayer({
    options = {
        {
	    icon = 'fa-solid fa-ring',
	    label = 'Poser un bracelet éléctronique',
            job = 'police',
            item = 'anklet',
	    canInteract = function(ent)
                local playerId = GetPlayerServerId(NetworkGetPlayerIndexFromPed(ent))

                local p = promise.new()
                QBCore.Functions.TriggerCallback('police:server:playerdata', function(result)
                    p:resolve(result)
                end, playerId)
                local res = Citizen.Await(p)

		return QBCore.Functions.GetPlayerData().job.onduty and IsPedAPlayer(ent) and not IsPedInAnyVehicle(ent) and not IsPedInAnyVehicle(PlayerPedId()) and not isHandcuffed and not isEscorted and not res.metadata["tracker"]
	    end,
            action = function(ent)
                local playerId = GetPlayerServerId(NetworkGetPlayerIndexFromPed(ent))
                TriggerServerEvent("police:server:addTracker", playerId, true)
            end
        },
        {
	    icon = 'fa-solid fa-ring',
	    label = 'retirer le bracelet éléctronique',
            job = 'police',
	    canInteract = function(ent)
                local playerId = GetPlayerServerId(NetworkGetPlayerIndexFromPed(ent))
                local p = promise.new()
                QBCore.Functions.TriggerCallback('police:server:playerdata', function(result)
                    p:resolve(result)
                end, playerId)

                local res = Citizen.Await(p)

	        return QBCore.Functions.GetPlayerData().job.onduty and IsPedAPlayer(ent) and not IsPedInAnyVehicle(ent) and not IsPedInAnyVehicle(PlayerPedId()) and not isHandcuffed and not isEscorted and res.metadata["tracker"]
	    end,
            action = function(ent)
                local playerId = GetPlayerServerId(NetworkGetPlayerIndexFromPed(ent))
                TriggerServerEvent("police:server:removeTracker", playerId, true)
            end
        }
    },
    distance = 1,
})
```

**To Reproduce**
1. write an AddGlobalPlayer export
2. add two options with a promise and a citizen.await() function in the canInteract function
3. Enjoy

**Expected behavior**
Just see actions on players

**Screenshots**

**Additional context**
This export work if i comment one of the two Citizen.await()
I also checked if change the var name or move the code in a function and call the function change anything but it still broken

**Comment by BerkieBb** [comment]
So when you use Citizen.Await it won't show the options anymore?

**Comment by skrilax91** [comment]
Yes, if I use only one citizen.await in the export I see options but if use two or more time this function no options appear, I have no error on the server or client console

**Comment by BerkieBb** [comment]
You can't use more than one Citizen.Await in one function

**Comment by skrilax91** [comment]
I know, but like you see in the code I have posted I use only one citizen.await in function, each one is in a canInteract function, if I understand I need to export each option separately?

**Comment by BerkieBb** [comment]
Does res.metadata["tracker"] return the right thing?

**Comment by skrilax91** [comment]
Yes, it return true or false, I've tested with just one citizen.await and the two actions work if I comment the other citizen.await

**Comment by BerkieBb** [comment]
This is an issue with asynchronous code trying to run in a function which is not running asynchronously, you will have to code around this by using non-asynchronous code or using code from other resources (e.g. exports)
