### ISSUE TITLE
[BUG] error loading into server after an update to target 

### ISSUE THREAD

**Issue by JYNKZIE** [BerkieBb/qb-target#113]
**Describe the bug**
script error upon loading into the server after a restart

**To Reproduce**
-update qb-target
-load into server after it starts up

**Expected behavior**
cannot use atms nor shops, no shops seem to work

**Screenshots**
![image](https://user-images.githubusercontent.com/98498564/161411116-c768ec3a-8f5f-4a8c-9401-01f261e63200.png)

**Comment by BerkieBb** [comment]
This seems like you have a wrong format for the function on that line, you could show me what's on that line?

**Comment by JYNKZIE** [comment]
`exports("RemoveZone", RemoveZone)

local function SetOptions(tbl, distance, options)
	for _, v in pairs(options) do
		if v.required_item then
			v.item = v.required_item
			v.required_item = nil
		end
		if not v.distance or v.distance > distance then v.distance = distance end
		tbl[v.label] = v
	end
end
`

443 would be `tbl[v.label] = v`

**Comment by BerkieBb** [comment]
That could be from a few options, can you make sure all of your target options have a label property set

**Comment by JYNKZIE** [comment]
within init, everything has a label set. not sure what my issue is xD
 i appreciate you !

**Comment by BerkieBb** [comment]
Is this still an issue?

**Comment by JYNKZIE** [comment]
No I fixed it by redoing the entire list and updated the script. Thank you 🙏
