### ISSUE TITLE
[SUPPORT] - Pressing on ALT not showing the eye.

### ISSUE THREAD

**Issue by L1R26** [BerkieBb/qb-target#119]
**Problem:**
I just updated to the new target and configured it to my script, now when pressing ALT nothing happens.
No errors in cmd and console.

**Wanted Outcome:**
Explain here what you want it to do

**Current Point:**
All information about where you are now with your problem goes here

**Screenshots:**
If applicable, add screenshots to help explain your problem

**Additional context:**
Before updating to the new one I was using very old version.. but I just think something is blocking it in the new target script.

**Comment by BerkieBb** [comment]
Is your qb-core updated

**Comment by L1R26** [comment]
> Is your qb-core updated

Hey, No.. using the one from 5 months ago. 
I tried to update to the new one but some of my scrips fucked up

**Comment by BerkieBb** [comment]
That's your problem

**Comment by BerkieBb** [comment]
Update it and fix the scripts that get problems instead of avoiding it, the newest qb-core has since had a lot of security changes and good features added

**Comment by BerkieBb** [comment]
Go to the qbcore discord if you need any more support on that
https://discord.gg/qbcore
