### ISSUE TITLE
[BUG] Raycast not blocked by walls or obstacles in certain mappings

### ISSUE THREAD

**Issue by zf-development** [BerkieBb/qb-target#122]
**Describe the bug**
The raycast detection is only blocked by props/entities in certain mappings.
When trying to target a wall in certain mappings, it doesn't work. I can make a target on a wall for playing animations.

1. Add a BoxZone on a wall in a added MLO.
2. Try to target it.
3. Observe that it doesn't work.

Nothing.

![image](https://user-images.githubusercontent.com/48424078/164989291-2b0957d4-55fb-423e-8795-2acb2ceb0931.png)

**Comment by BerkieBb** [comment]
That's probably because the map isn't made very good, so they didn't think about making every prop in it have the appropriate flag for the raycast to interact with, or it's another flag which I haven't discovered
