### ISSUE TITLE
[BUG] 5.3.7 Events are not triggering

### ISSUE THREAD

**Issue by devin-monro** [BerkieBb/qb-target#125]
**Describe the bug**
Events are no longer getting triggered when clicked/selected.

**To Reproduce**
Download 5.3.7, Create any export Target with an event trigger.
**Expected behavior**
Event to be ran when clicked/selected.

**Additional context**
I added some debug text to the client.lua NUI Callback for "selectTarget"
`local data = sendData[option]`
`print(data.event)`

Results in an "attempt to index a nil value (local 'data')
I'll dig a little more to see if I can find out why. Possibly something to do with the recent eventListener changes?

**Comment by devin-monro** [comment]
I looped through the split array and saw that the option index was on index 2 not 1. Changing it to 2 worked for me.
```body: JSON.stringify(split[2])```

**Comment by BerkieBb** [comment]
No, just redownload now, it should be fixed with the latest source code

**Comment by BerkieBb** [comment]
I'll test it again in a moment

**Comment by BerkieBb** [comment]
Fixed with https://github.com/BerkieBb/qb-target/releases/tag/5.3.8
