### ISSUE TITLE
[BUG] Can't change color and can't interact unless I close an dopen the eye

### ISSUE THREAD

**Issue by SrPeterr** [BerkieBb/qb-target#126]
**Describe the bug**
Well, on the last version I could change the color of the eye, here its staying blue, I have changed it on the `init.lua`
The second thing is that on the last version, I could keep the eye active and go interact with new props, peds, or what ever, now I have to close it and opened it. Is this intencional? 

**Screenshots**
https://streamable.com/f36iye

**init.lua colors:**
```
Config.DrawColor = {255, 255, 255, 255}

Config.SuccessDrawColor = {1, 172, 159, 255}

Config.OutlineColor = {255, 255, 255, 255}
```
**Version:** 5.3.8
Haven't changed anything just the RGB colors

**Comment by BerkieBb** [comment]
Those configs are for the circle that's drawn on polyzones when Config.DrawSprite is true, the actual color of the eye is in qb-target/html/js/app.js

**Comment by SrPeterr** [comment]
Ok, so I'm a bit lost, what are those 3 config for?

**Comment by BerkieBb** [comment]
For the circle hint on polyzones, besides the outlinecolor, that's for outlines around entities when Config.EnableOutline is true

**Comment by BerkieBb** [comment]
If you read the comment above it should tell you that

**Comment by BerkieBb** [comment]
But all three have nothing to do with the eye itself

**Comment by SrPeterr** [comment]
Ok, got it! Thanks and sorry for the mistake...

**Comment by BerkieBb** [comment]
No problem, I get that you can be confused with it
