### ISSUE TITLE
hello you accept new suggest

### ISSUE THREAD

**Issue by vanillla1** [BerkieBb/qb-target#17]
hello
thank you
i have new pull for add custem animation for trigger

        type = "client",
        event = "Toggle:Duty",
        icon = "fas fa-sign-in-alt",
        label = "Sign In",
        job = "police",
       animation = "WORLD_HUMAN_COP_IDLES", -- not requrment

and thank you

**Comment by BerkieBb** [comment]
Good idea, I'll work on it!

**Comment by vanillla1** [comment]
and can add in wiki how use grade job and inventory how to used

**Comment by BerkieBb** [comment]
> and can add in wiki how use grade job and inventory how to used

That's already in the examples.md
But about that idea of animations, it's better to trigger it from an event with qb-target as it's pointless with this because of optimization
