### ISSUE TITLE
nh-context integration issue

### ISSUE THREAD

**Issue by Ohague22** [BerkieBb/qb-target#26]
Whenever using qb-target to setup a car spawner with nh-context it locks the camera when you spawn the car in and keeps the wheels turning, you have to press left click again to bring back the camera movement. 

https://streamable.com/g38u5s

**Comment by BerkieBb** [comment]
Can you check if v2.5.0 fixes this issue?

**Comment by papabendi** [comment]
Seems to have fixed it for me

**Comment by Ohague22** [comment]
yes that seems to have fixed it, thanks. Sorry for late reply
