### ISSUE TITLE
Peds not spawning

### ISSUE THREAD

**Issue by Slay3rIQ** [BerkieBb/qb-target#51]
I have added some peds but since the last updates they are not spawning anymore. I dont get errors on my console either.

![image](https://user-images.githubusercontent.com/90642225/139532578-fbd8c32a-0f2e-480b-bf20-af7b779b2acb.png)

**Comment by BerkieBb** [comment]
Closed for v4.0.0 release, please test that and open an issue again if you have the issue still

**Comment by Slay3rIQ** [comment]
Still not

![image](https://user-images.githubusercontent.com/90642225/139606240-325efb63-2efd-42ae-8378-6393e13d04e2.png)

**Comment by Slay3rIQ** [comment]
> Closed for v4.0.0 release, please test that and open an issue again if you have the issue still

Still not

![image](https://user-images.githubusercontent.com/90642225/139606256-e3183af3-25cd-49ed-a46f-a47672b49ce0.png)
