### ISSUE TITLE
Dosen't work if qbcore

### ISSUE THREAD

**Issue by Howsn** [BerkieBb/qb-target#55]
Hello! Thanks for this awsome script!

I have a litle problem, I have to run the script as standalone for it to work on my qbcore server.
When I set it to qbcore I cant open the eye.

But when running the script as standalone I cant get the ( job = "police", ) to work.

**Comment by BlueSky-fur** [comment]
what?

**Comment by BerkieBb** [comment]
Show me your target options and config

**Comment by BerkieBb** [comment]
Update to V5.0.0
