### ISSUE TITLE
Items not saving on dropped

### ISSUE THREAD

**Issue by copofiscool** [BerkieBb/qb-target#56]
If Item is requied and you start script without the item it doesnt work.
And if you drop the item you can still do the task that requires the item

**Comment by davidxd33** [comment]
Refresh the player object to fix:

`	function Functions.ItemCount(item)
        PlayerData = QBCore.Functions.GetPlayerData()
		for k, v in pairs(PlayerData.items) do
			if v.name == item then
				return v.amount
			end
		end
		return 0
	end
`

**Comment by BerkieBb** [comment]
Will be fixed with the next update, keep watching for it
