### ISSUE TITLE
[Feature Request] Don't close menu after MenuControlKey press

### ISSUE THREAD

**Issue by helenclarko** [BerkieBb/qb-target#57]
I think qb-target was previously setup like this, but now I have to keep the MenuControlKey held down in order to use this.

I personally have my MenuControlKey tied to middle mouse click which makes it a little bit of a dance to select anything.
Is there a way I can get is to stay open after MenuControlKey has been pushed?

**Comment by BerkieBb** [comment]
I do this to make sure the eye never gets stuck on your screen

**Comment by ImpulseFPS** [comment]
I was wondering the same thing if you are gonna do target without having to hold the key when the menu is present for the eye to stay open.

**Comment by BerkieBb** [comment]
No, keymapping makes it disable when not held and I don't want to go writing something around it and this way the eye doesn't get stuck ever
