### ISSUE TITLE
only works for select people on qbcore

### ISSUE THREAD

**Issue by kingofkingzcd** [BerkieBb/qb-target#58]
only works for like 3 of 10 people. any help is appreciated. no errors client or server side. for the people it works for it is perfect. then the rest cant even get the eye to show up.

**Comment by Exiledtemplar** [comment]
same, we have some folks the eye comes up but no cursor and ours its fine

**Comment by jnccloud** [comment]
Have these users check their mouse setting in FiveM. I think there are options like Direct Input, Windows, etc. Look at one that works like yours for example, and then have them try the same setting.
