### ISSUE TITLE
Weird issue with Box heights.

### ISSUE THREAD

**Issue by BlueSky-fur** [BerkieBb/qb-target#62]
im trying to change the height at where the box is seen (im using debugPoly) but no matter what i do, i can move the box around changing vector3 but i cant move it up or down. is that known?

**Comment by BerkieBb** [comment]
Have you tried using minZ and maxZ?

**Comment by BlueSky-fur** [comment]
Ohhh, right! i literally ALWAYS forget about these.. it worked *insert facepalm here* Sorry!
