### ISSUE TITLE
BUG: cb is not defined app.js:50

### ISSUE THREAD

**Issue by davidxd33** [BerkieBb/qb-target#67]
So when using target I get this error every time however nothing appears to break other than just the error being thrown. This is on all my boxzone targets.

![](https://i.imgur.com/Ebpe6px.png)

**Comment by BerkieBb** [comment]
https://github.com/BerkieBb/qb-target/commit/99a513aadde5bef0d39f7f4e4faf4c03af641480
Could you test this fix?

**Comment by davidxd33** [comment]
> [99a513a](https://github.com/BerkieBb/qb-target/commit/99a513aadde5bef0d39f7f4e4faf4c03af641480) Could you test this fix?

That fixes it, I wasn't sure if that cb function was required for another feat. Thanks for the quick fix on xmas.

**Comment by BerkieBb** [comment]
No problem
