### ISSUE TITLE
Make qb-target work with qb-shops (or something similar)

### ISSUE THREAD

**Issue by justkryptic** [BerkieBb/qb-target#68]
Hello,

This is not an issue, more so a suggestion/question looking for help.

I am fairly new to using qb-target, but I am wondering if anyone knows how to make it work with qb-shops.What I am trying to do is have specific peds open specific shops where a player can buy those items.

For example: Let's say there is I had this ped: "a_m_m_indian_01" at every Ammunation shop in my server. When people use the eye it would open the Gun Shop associated with what items should be purchasable in my qb-shops config.

The closest I have been able to do is to make the eye open the normal players inventory when using it, but that doesn't show items to purchase. Any help would be much appreciated as I have tried to figure this out for a week now and haven't had any success yet.

**Comment by BerkieBb** [comment]
qb-shops will get a target update, so stay tuned for that
