### ISSUE TITLE
Is there a way to use onPlayerInOut?

### ISSUE THREAD

**Issue by cademullen** [BerkieBb/qb-target#70]
Are you able to use onPlayerInOut with a BoxZone created from berkie-target?

**Comment by BerkieBb** [comment]
No not at the moment

**Comment by BerkieBb** [comment]
Added in V5.1.0, commit will come in 10 minutes

**Comment by BerkieBb** [comment]
You use it like this
`local zone = exports['qb-target']:AddBoxZone...etc`
