### ISSUE TITLE
RemovePed

### ISSUE THREAD

**Issue by Topnetworks** [BerkieBb/qb-target#73]
i have been trying to use RemovePed, this shows no such Export.. but its listed in the Examples..

**Comment by BerkieBb** [comment]
It has no export setup, I'll make one

**Comment by Topnetworks** [comment]
> It has no export setup, I'll make one

Good job mate, i wasnt sure about this its only reason i asked. Cheers

**Comment by BerkieBb** [comment]
Added in V5.1.0, the commit will come in 10 minutes
