### ISSUE TITLE
AddComboZone: table index is nil

### ISSUE THREAD

**Issue by hdsunbed** [BerkieBb/qb-target#74]
I have been trying to test the AddCombZone export from the templates.md and keep getting "table index is nil" referencing client.lua line 414 

`local function AddComboZone(zones, options, targetoptions)
	Zones[name] = ComboZone:Create(zones, options) <
	targetoptions.distance = targetoptions.distance or Config.MaxDistance
	Zones[name].targetoptions = targetoptions
end

exports("AddComboZone", AddComboZone)`

I believe it is due to Zones[name] as it doesnt enter the table and would expect some kind of a for loop.

Am i doing something wrong or am i missing something?

**Comment by BerkieBb** [comment]
Show me your options that add the combo zone

**Comment by coffee-hunter** [comment]
I am having the same issue and this is my code

`            
if dist <= 2 then
                if Config.Target then
                    local zone1 = BoxZone:Create(vector3(-284.21, 2208.74, 129.81), 1.0, 1.0, {
                        name = "plant1",
                        debugPoly = false
                    })
                    local zone2 = BoxZone:Create(vector3(-300.85, 2206.86, 132.2), 1.0, 1.0, {
                        name = "plant2",
                        debugPoly = false
                    })
                    local zone3 = BoxZone:Create(vector3(-290.68, 2221.34, 131.26), 1.0, 1.0, {
                        name = "plant3",
                        debugPoly = false
                    })
                    local zone4 = BoxZone:Create(vector3(-304.49, 2232.19, 131.83), 1.0, 1.0, {
                        name = "plant4",
                        debugPoly = false
                    })
                    local zones = {zone1, zone2, zone3, zone4}
                    exports['qb-target']:AddComboZone(zones, {
                        name = "harvestWeed",
                        debugPoly = false,
                    }, {
                        options = {
                            {
                                type = "client",
                                event = "chq_drugs:harvestWeed",
                                icon = "fas fa-leaf",
                                label = "Harvest Cannabis"
                            }
                        },
                        distance = 2.0
                    })
                end
            end
`

**Comment by BerkieBb** [comment]
My fault, seen a problem in there

**Comment by BerkieBb** [comment]
https://github.com/BerkieBb/qb-target/commit/46340c5dccc7d1593486d2f6f65dbad59bd5cd01
Fixed it for you
