### ISSUE TITLE
Can't user target

### ISSUE THREAD

**Issue by Coffister** [BerkieBb/qb-target#75]
Hi, today i downloaded this qb-target to test it out. It's working for other players but i can't use it. The problem occured after one restart of a server without even touching the qb-target files. It's not a keybind problem. Do anybody have something to fix it on my side?

Thank you, Coffister.

**Comment by BerkieBb** [comment]
Download the new version and test it

**Comment by colonelnl** [comment]
Same problem.

**Comment by BerkieBb** [comment]
Is this still a problem?

**Comment by Motofam** [comment]
yes still a problem across many cities i have checked with people and not sure what issue is. didnt change anything or add anything. downloaded fresh qb-target and no target

**Comment by RPShaggy** [comment]
I have this issue, any solutions?
