### ISSUE TITLE
Question about template

### ISSUE THREAD

**Issue by KingRyuShin** [BerkieBb/qb-target#78]
@BerkieBb 
I got this inside my LegacyFuel to add this to my car
![image](https://user-images.githubusercontent.com/42899923/149648043-c2966a96-5283-4ae9-9156-f13ac98d3ec3.png)
![image](https://user-images.githubusercontent.com/42899923/149648035-ddebc47a-b8f2-446f-9904-c282c879e11f.png)

I also have this script inside another files to add the door option on my vehicle but it doesn't show them when i use the target.
![image](https://user-images.githubusercontent.com/42899923/149648072-bc1a9427-cc6a-4e1f-a421-a1f3837083ab.png)

but sometime, depending on where i click with my target, it show everything
![image](https://user-images.githubusercontent.com/42899923/149648088-be919900-01fe-41ba-b9af-9ba04d201bb1.png)

**Comment by BerkieBb** [comment]
You can remove all the second ones because those are included with qb-target already, you can enable them by setting the `Config.EnableDefaultOptions` to true

**Comment by KingRyuShin** [comment]
Okay I will delete them.
But I still don't know why the option for the door/trunk/hood doesn't appear with my refuel vehicle options, it's either the door or the refuel option and depending how many time i try on the car, sometime i will get both together.

**Comment by BerkieBb** [comment]
Then it is because it picks up another bone or the distance for the fuel is too low

**Comment by KingRyuShin** [comment]
Seem to have found one of the problem to my problem..
Look like it doesn't update the qb-target export when restarting the script, like it doesn't load what I added.

**Comment by BerkieBb** [comment]
You need to restart qb-target first and then restart your script that the export is in

**Comment by KingRyuShin** [comment]
Another problem..
trying to use model to open atm.. eye doesn't show up but the model name are good.

    

> ['OpenATM'] = {
>         models = {
>             "prop_atm_01", 
> 			"prop_atm_02",
> 			"prop_atm_03",
> 			"prop_fleeca_atm"
>         },
>         options = {
>             {
>                 type = "client",
>                 event = "qb-atms:client:loadATM",
>                 icon = "fas fa-hands",
>                 label = "Utiliser ATM",
>             },
>         },
>         distance = 2.5
>     },

I've also tried with Config.TargetEntities while the atm entities number is -1126237515

and nothing show up

**Comment by BerkieBb** [comment]
If you have NVE, remove the atm package from it as NVE animated atms and that messes with the raycast

**Comment by KingRyuShin** [comment]
> If you have NVE, remove the atm package from it as NVE animated atms and that messes with the raycast

Thank you, that was actually the problem, i had NVE
