### ISSUE TITLE
hello , no issue , just a suggetion to see if it is possible

### ISSUE THREAD

**Issue by Maureks** [BerkieBb/qb-target#79]
A qb-target function for the police to cuff people , to save time going to radial menu or using the command /cuff

I have tried it in many ways, but i can't seem to make it work

I tried it like this :

["targetmodel1"] = {
    models = {"mp_m_freemode_01","mp_f_freemode_01"},
    options = {
        {
		    type = "client",
            event = "police:client:CuffPlayerSoft",
            icon = "fas fa-hands",
            label = "Cuff",
            job = "police",
        },
    },
    distance = 2.5,
},
I've tried also with:

type = "command"
event = "cuff"

I haven't tried with command "sc" (soft cuff) but i dont see much diference from the "cuff" command

Am I doing something wrong? Is something missing? What can I do? Is it even possible?

Thanks in advance, and sorry for the bad english!

**Comment by BerkieBb** [comment]
Don't do targetmodels, use global player options

**Comment by BerkieBb** [comment]
And that event requires arguments that qb-target can't provide using this way

**Comment by Maureks** [comment]
Oh okok ! Thanks for the attention ! 
If it's ever possible , I'd be glad to test it !  ​

P.S - Non related, but I have qb-target all updated, and it gives me this error:

SCRIPT ERROR : @qb-target/client.lua:594: bad argument #1 'for iterator' (table expected, got nil)

But everything works well, players can do everything they are supposed to , I don't know if it's just for me , just asking! 
Thanks once again

**Comment by BerkieBb** [comment]
That errors means you misused a function, show a screenshot of what the code is on that line and around it

**Comment by Maureks** [comment]
Here's a screenshot of the client.lua :
![image](https://user-images.githubusercontent.com/84512488/151637140-6ac0b822-f013-465b-983a-ecf5b79dc6a0.png)

**Comment by Maureks** [comment]
I haven't made any changes , maybe I didn't updated right?

**Comment by BerkieBb** [comment]
No it's because you didn't use a config right

**Comment by Maureks** [comment]
Ah forget it ! I'am so sorry ! , It was a couple functions in the init.lua that were not good , I've changed them , restarted the server, and now no errors appear!
I'am sorry for wasting your time ! 
Thank you so much !
