### ISSUE TITLE
No Target

### ISSUE THREAD

**Issue by slymerog** [BerkieBb/qb-target#84]
Hi,

I have installed this like any other resource but sadly cant seem to get it working. I was using another 3rd Eye but wanted to replace it with this. I removed the old one, and removed the prior QB-target, and replaced it with yours. The resource starts up, but nothing when pressing LALT / trying to use 3rd Eye. I'm sorry, a little new here to QBCore & FiveM in general, if there are better ways I could trouble shoot this problem feel free to let me know! (:

**Comment by BerkieBb** [comment]
Make sure your qb-core is updated

**Comment by helenclarko** [comment]
If you are upgrading from a prior qb-target to the latest, clear your server cache too. I found this to help.
