### ISSUE TITLE
Do not open

### ISSUE THREAD

**Issue by catiagomes94a** [BerkieBb/qb-target#85]
Hello i downloaded this qb-target the problem occured after one restart of a server without even touching the qb-target files. I don't know what it could be. I can't use it after this.

**Comment by BerkieBb** [comment]
What problem?

**Comment by n4n-0** [comment]
Yeah I add a target zone and press l-alt and nothing happens. It looks like it sending a message to client console but its blank so Im not sure.

**Comment by BerkieBb** [comment]
Can you make a video?
