### ISSUE TITLE
Peds Not Spawning

### ISSUE THREAD

**Issue by xMaddMackx** [BerkieBb/qb-target#86]
Script was working fine until after a restart. Did something update in the way peds spawn?

https://i.imgur.com/rTe6PLY.png
https://i.imgur.com/q7Kb3D2.png
https://i.imgur.com/oGb3fBl.png

**Comment by BerkieBb** [comment]
This error you posted doesn't seem to relate to the title, but please show your targetmodels config and globalplayer optionz

**Comment by xMaddMackx** [comment]
Config.TargetModels = {
    ["24/7 shops"] = {
        models = {
            "mp_m_shopkeep_01",
        },
        options = {
            {
                type = "client",
                event = "qb-shops:marketshop",
                icon = "fas fa-store",
                label = "Buy Items",
            },
        },
        distance = 2.5,
    },
    ["ammunation shops"] = {
        models = {
            "s_m_y_ammucity_01",
        },
        options = {
            {
                type = "client",
                event = "qb-shops:marketshop",
                icon = "fas fa-shopping-cart",
                label = "Buy Weapons",
            },
        },
        distance = 2.5,
    },
	["black market"] = {
        models = {
            "u_m_y_pogo_01",
        },
        options = {
            {
                type = "client",
                event = "qb-shops:marketshop",
                icon = "fas fa-shopping-cart",
                label = "Black Market",
            },
        },
        distance = 2.5,
    },
	["oneandonlyhuntingshop"] = {
        models = {
            "a_m_m_indian_01",
        },
        options = {
            {
                type = "client",
                event = "qb-shops:marketshop",
                icon = "fas fa-store",
                label = "Buy Items",
            },
        },
        distance = 2.5,
    },
    ["weedshop"] = {
        models = {
            "cs_orleans",
        },
        options = {
            {
                type = "client",
                event = "qb-shops:marketshop",
                icon = "fas fa-wrench",
                label = "Buy Items",
            },
        },
        distance = 2.5,
    },
	["bestbuds"] = {
        models = {
            "cs_denise",
        },
        options = {
            {
                type = "client",
                event = "qb-shops:marketshop",
                icon = "fas fa-wrench",
                label = "Buy Items",
            },
        },
        distance = 2.5,
    },
	["casino"] = {
        models = {
            "ig_tomcasino",
        },
        options = {
            {
                type = "client",
                event = "qb-shops:marketshop",
                icon = "fas fa-store",
                label = "Buy Items",
            },
        },
        distance = 2.5,
    },
	["casino2"] = {
        models = {
            "s_m_y_casino_01",
        },
        options = {
            {
                type = "client",
                event = "qb-shops:marketshop",
                icon = "fas fa-store",
                label = "Buy Items",
            },
        },
        distance = 3.5,
    },
    ["youtool shops"] = {
        models = {
            "s_m_m_lathandy_01",
        },
        options = {
            {
                type = "client",
                event = "qb-shops:marketshop",
                icon = "fas fa-wrench",
                label = "Buy Tools",
            },
        },
        distance = 2.5,
    },
	["burgershotgarage"] = {
		models = {
			"ig_floyd",
		},
		options = {
			{
				type = "client",
				event = "garage:BurgerShotGarage",
				icon = "fas fa-car",
				label = "BurgerShot Garage",
				job = "burgershot",
			}
		},
		distance = 2.5,
	},
    ["sea world"] = {
        models = {
            "cs_dom",
        },
        options = {
            {
                type = "client",
                event = "qb-shops:marketshop",
                icon = "fas fa-circle",
                label = "Buy Gear",
            },
        },
        distance = 2.5,
    },
	-----ATMSS-----
	["ATM"] = {
		models = { `prop_atm_01`, `prop_atm_02`, `prop_atm_03`, `prop_fleeca_atm`,},
		options = {
			{
				type = "command",
				event = "atm",
				parameters = {},
				icon = "fab fa-cc-visa",
				label = "Use ATM",
			},
		},
		distance = 1.5
	},
	-----ATMSS END-----
	
	------Banks----
	["Banks"] = {
		models = {
			`v_corp_fleeca_display`,
	  
		},
		options = {
			{
				type = "client",
				event = "qb-banking:openBankScreen",
				parameters = {},
				icon = "fas fa-piggy-bank",
				label = "Open Bank",
			},
		},
		distance = 1.5
	},
	["trashsearch"] = {
        models = {
	-1096777189,
	666561306,
	1437508529,
	-1426008804,
	-228596739,
	161465839,
	651101403,
        -58485588,
        218085040,
        -206690185,

        },
        options = {
            {
                type = "client",
                event = "qb-trashsearch:client:searchtrash",
                icon = "fas fa-dumpster",
                label = "Dumpster Dive",
            },
        },
        distance = 1.0
    },
	------Banks END----
}

Config.GlobalPedOptions = {

}

Config.GlobalVehicleOptions = {

}

Config.GlobalObjectOptions = {

}

Config.GlobalPlayerOptions = {
	options = {
		{
		type = "client",
		event = "qb-phone:client:GiveContactDetails",
		icon = 'fas fa-phone',
		label = 'Give Contact Details',
		item = 'phone',
		
		},
		{
		type = "client",
		event = "police:client:SearchPlayer",
		icon ='fas fa-id-card',
		label = 'Search Person',
		job = 'police',
		},
		distance = 2.0
		},
}

Config.GlobalPlayerOptions = {
	options = {
		{
		type = "client",
		event = "qb-phone:client:GiveContactDetails",
		icon = 'fas fa-phone',
		label = 'Give Contact Details',
		item = 'phone',
		
		},
		{
		type = "client",
		event = "police:client:SearchPlayer",
		icon ='fas fa-id-card',
		label = 'Search Person',
		job = 'police',
		},
		distance = 2.0
		},
}

**Comment by BerkieBb** [comment]
Please use code blocks
\```lua
  -- code
\```

Translates to

```lua
  -- code
```

**Comment by xMaddMackx** [comment]
```lua
Config.GlobalPlayerOptions = {
	options = {
		{
		type = "client",
		event = "qb-phone:client:GiveContactDetails",
		icon = 'fas fa-phone',
		label = 'Give Contact Details',
		item = 'phone',
		
		},
		{
		type = "client",
		event = "police:client:SearchPlayer",
		icon ='fas fa-id-card',
		label = 'Search Person',
		job = 'police',
		},
		distance = 2.0
		},
}

Config.TargetModels = {
    ["24/7 shops"] = {
        models = {
            "mp_m_shopkeep_01",
        },
        options = {
            {
                type = "client",
                event = "qb-shops:marketshop",
                icon = "fas fa-store",
                label = "Buy Items",
            },
        },
        distance = 2.5,
    },
    ["ammunation shops"] = {
        models = {
            "s_m_y_ammucity_01",
        },
        options = {
            {
                type = "client",
                event = "qb-shops:marketshop",
                icon = "fas fa-shopping-cart",
                label = "Buy Weapons",
            },
        },
        distance = 2.5,
    },
	["black market"] = {
        models = {
            "u_m_y_pogo_01",
        },
        options = {
            {
                type = "client",
                event = "qb-shops:marketshop",
                icon = "fas fa-shopping-cart",
                label = "Black Market",
            },
        },
        distance = 2.5,
    },
	["oneandonlyhuntingshop"] = {
        models = {
            "a_m_m_indian_01",
        },
        options = {
            {
                type = "client",
                event = "qb-shops:marketshop",
                icon = "fas fa-store",
                label = "Buy Items",
            },
        },
        distance = 2.5,
    },
    ["weedshop"] = {
        models = {
            "cs_orleans",
        },
        options = {
            {
                type = "client",
                event = "qb-shops:marketshop",
                icon = "fas fa-wrench",
                label = "Buy Items",
            },
        },
        distance = 2.5,
    },
	["bestbuds"] = {
        models = {
            "cs_denise",
        },
        options = {
            {
                type = "client",
                event = "qb-shops:marketshop",
                icon = "fas fa-wrench",
                label = "Buy Items",
            },
        },
        distance = 2.5,
    },
	["casino"] = {
        models = {
            "ig_tomcasino",
        },
        options = {
            {
                type = "client",
                event = "qb-shops:marketshop",
                icon = "fas fa-store",
                label = "Buy Items",
            },
        },
        distance = 2.5,
    },
	["casino2"] = {
        models = {
            "s_m_y_casino_01",
        },
        options = {
            {
                type = "client",
                event = "qb-shops:marketshop",
                icon = "fas fa-store",
                label = "Buy Items",
            },
        },
        distance = 3.5,
    },
    ["youtool shops"] = {
        models = {
            "s_m_m_lathandy_01",
        },
        options = {
            {
                type = "client",
                event = "qb-shops:marketshop",
                icon = "fas fa-wrench",
                label = "Buy Tools",
            },
        },
        distance = 2.5,
    },
	["burgershotgarage"] = {
		models = {
			"ig_floyd",
		},
		options = {
			{
				type = "client",
				event = "garage:BurgerShotGarage",
				icon = "fas fa-car",
				label = "BurgerShot Garage",
				job = "burgershot",
			}
		},
		distance = 2.5,
	},
    ["sea world"] = {
        models = {
            "cs_dom",
        },
        options = {
            {
                type = "client",
                event = "qb-shops:marketshop",
                icon = "fas fa-circle",
                label = "Buy Gear",
            },
        },
        distance = 2.5,
    },
	-----ATMSS-----
	["ATM"] = {
		models = { `prop_atm_01`, `prop_atm_02`, `prop_atm_03`, `prop_fleeca_atm`,},
		options = {
			{
				type = "command",
				event = "atm",
				parameters = {},
				icon = "fab fa-cc-visa",
				label = "Use ATM",
			},
		},
		distance = 1.5
	},
	-----ATMSS END-----
	
	------Banks----
	["Banks"] = {
		models = {
			`v_corp_fleeca_display`,
	  
		},
		options = {
			{
				type = "client",
				event = "qb-banking:openBankScreen",
				parameters = {},
				icon = "fas fa-piggy-bank",
				label = "Open Bank",
			},
		},
		distance = 1.5
	},
	["trashsearch"] = {
        models = {
	-1096777189,
	666561306,
	1437508529,
	-1426008804,
	-228596739,
	161465839,
	651101403,
        -58485588,
        218085040,
        -206690185,

        },
        options = {
            {
                type = "client",
                event = "qb-trashsearch:client:searchtrash",
                icon = "fas fa-dumpster",
                label = "Dumpster Dive",
            },
        },
        distance = 1.0
    },
	------Banks END----
}
```

**Comment by BerkieBb** [comment]
The distance in the GlobalPlayerOptions needs to be outside of the options table, not inside

**Comment by xMaddMackx** [comment]
Is this now correct?

```lua
Config.GlobalPlayerOptions = {
	options = {
		{
		type = "client",
		event = "qb-phone:client:GiveContactDetails",
		icon = 'fas fa-phone',
		label = 'Give Contact Details',
		item = 'phone',
		
		},
		{
		type = "client",
		event = "police:client:SearchPlayer",
		icon ='fas fa-id-card',
		label = 'Search Person',
		job = 'police',
		},
	},
	distance = 2.0,
}
```
