### ISSUE TITLE
Passing Arguments Through qb-target Export

### ISSUE THREAD

**Issue by ch0sguy** [BerkieBb/qb-target#88]
Are you capable of doing as the title suggests? I have a scenario in which I want the player to pick up an order from a specific location, optimally using qb-target to interact with something to obtain it, but this requires parameters to be passed through the server function, as such:
```
exports['qb-target']:AddTargetModel('a_f_o_salton_01', {
		options = {
			{
                type = "server",
				event = "merty:esyaekle", -- where this event requires two parameters, item and count, to be passed
				icon = "fas fa-burger",
				label = "Pick Up Order",
                item = item,
                count = count,
			},
		},
			distance = 2.5 
	})
```

Is this possible, and can it be obtained through AddTargetModel, or might it require a different format using qb-target?

Thanks

**Comment by ch0sguy** [comment]
i've seen qb-menu utilize arguments as such:
```
event = "whatever:whatever",
args = {
      param = param
}
```
I assume this works for qb-target as well?

**Comment by BerkieBb** [comment]
Yes but is is not needed in the args table

**Comment by ch0sguy** [comment]
Is something like this what you're referring to?
```
event = {
         "event:server",
         item = item,
         count = count,
}
```
That's one variation I've attempted, that is, and it didn't seem to work.

**Comment by BerkieBb** [comment]
No

**Comment by BerkieBb** [comment]
qb-target always sends the table which the svent id located in as a parameter
