### ISSUE TITLE
[BUG]?.. Possible qb-target with peds

### ISSUE THREAD

**Issue by DanJackson78227** [BerkieBb/qb-target#96]
Hello BerkieB, I am trying to use qb-target to open the shop's inventory I am able to get the ped to spawn but I can't target the ped at all I have no errors nothing 

**Code From qb-target init.lua** 
Under the **Config.TargetModels** Section
["24/7 shops"] = {
        models = {
            "mp_m_shopkeep_01",
        },
        options = {
            {
                type = "client",
                event = "qb-shops:marketshop",
                icon = "fas fa-store",
                label = "Buy Items",
            },
        },
        distance = 2.5,
    },
   
I have more TargetModels Setup but didn't post them as they are the same just with different names
    
**Code from qb-target init.lua** 
under the **Config.Peds** section
{  -------Youtool Shop------
	model = `s_m_m_lathandy_01`,
	coords = vector4(45.48, -1748.85, 28.55, 55.1),
	gender = 'male',
	freeze = true,
	invincible = true,
	blockevents = true,
}, 

Again have more than one of these but they are the same 

**Modified qb-shops code**  client/main.lua

I have added 
RegisterNetEvent('qb-shops:marketshop')
AddEventhandlet('qb-shops:marketshop'.  function(shop, itemData, amount)
in place of 
RegisterNetEvent('qb-shops:marketshop', function()
but still nothing on the output side has changed

RegisterNetEvent('qb-shops:marketshop', function()
    local PlayerPed = PlayerPedId()
    local PlayerPos = GetEntityCoords(PlayerPed)
    for shop, _ in pairs(Config.Locations) do
        local position = Config.Locations[shop]["coords"]
        local products = Config.Locations[shop].products
        for _, loc in pairs(position) do
            local dist = #(PlayerPos - vector3(loc["x"], loc["y"], loc["z"]))
            if dist < 3 then
                local ShopItems = {}
                ShopItems.items = {}
                QBCore.Functions.TriggerCallback("qb-shops:server:getLicenseStatus", function(hasLicense, hasLicenseItem)
                    ShopItems.label = Config.Locations[shop]["label"]
                    if Config.Locations[shop].products == Config.Products["weapons"] then
                        if hasLicense and hasLicenseItem then
                            ShopItems.items = SetupItems(shop)
                            QBCore.Functions.Notify(Lang:t("success.dealer_verify"), "success")
                            Wait(500)
                        else
                            for i = 1, #products do
                                if not products[i].requiredJob then
                                    if not products[i].requiresLicense then
                                        ShopItems.items[#ShopItems.items + 1] = products[i]
                                    end
                                else
                                    for i2 = 1, #products[i].requiredJob do
                                        if QBCore.Functions.GetPlayerData().job.name == products[i].requiredJob[i2] and not products[i].requiresLicense then
                                            ShopItems.items[#ShopItems.items + 1] = products[i]
                                        end
                                    end
                                end
                            end
                            QBCore.Functions.Notify(Lang:t("error.dealer_decline"), "error")
                            Wait(500)
                            QBCore.Functions.Notify(Lang:t("error.talk_cop"), "error")
                            Wait(1000)
                        end
                    else
                        ShopItems.items = SetupItems(shop)
                    end
                    for k, v in pairs(ShopItems.items) do
                        ShopItems.items[k].slot = k
                    end
                    ShopItems.slots = 30
                    TriggerServerEvent("inventory:server:OpenInventory", "shop", "Itemshop_" .. shop, ShopItems)
                end)
            end
        end
    end
end)
I am just looking for some guidance possibly a personal chat or even discord DMS as I have a pretty solid coding background in javascript and PHP but am sorta new to Lua and this is my first time using qb-target. I have tried using exports inside the shop files I have tried polyzones nothing I do throws an error or opens the menu 

I do however know that the script is working because it works with cars and a fuel script that I have called lj-fuel

Any help would be greatly appreciated - Dan Jackson

**Comment by BerkieBb** [comment]
Update to v5.2.2

**Comment by DanJackson78227** [comment]
10-4 thank you sir I will leave this open until after I download to 5.2.2 and then let you know what happens

**Comment by DanJackson78227** [comment]
is everything else good with my code?

**Comment by DanJackson78227** [comment]
Thank you I appreciate it a lot :))))
