### ISSUE TITLE
[Suggestion] Target Hint

### ISSUE THREAD

**Issue by idunnoooooo** [BerkieBb/qb-target#98]
It would be amazing to have these hint circles in target basically when u hold target these circles appear at all targetable objects so people instead of searching targetable objects everywhere can just see where they can use target

![image](https://media.discordapp.net/attachments/900180032935325707/951068989780557854/1644705233828.png)

**Comment by Sc4r05** [comment]
yes that would be nice! i like the idea

**Comment by BerkieBb** [comment]
https://github.com/overextended/qtarget/pull/70
There is a pull request on qtarget (qb-target originates from qtarget and I maintain qtarget now aswell), so you could try that and let me know if it works good for you
