### ISSUE TITLE
[SUPPORT] raycast export

### ISSUE THREAD

**Issue by Kichoabro** [BerkieBb/qb-target#99]
How to use the raycast export? Because

`local entity = exports["qb-target"]:RaycastCamera(-1, GetEntityCoords(PlayerPedId()))`

doesn't work

**Comment by BerkieBb** [comment]
It does work but you're using the wrong return values, it doesn't return the entity in the first argument

**Comment by BerkieBb** [comment]
```lua
local flag, hitCoords, distance, entity, entityType = exports["qb-target"]:RaycastCamera(-1, GetEntityCoords(PlayerPedId()))
```
This is the format

**Comment by Kichoabro** [comment]
![das](https://user-images.githubusercontent.com/101333862/157663361-dc5a1fd0-51eb-4deb-80d6-fa2d07ef5072.png)

**Comment by BerkieBb** [comment]
Did you change something in the client.lua?

**Comment by Kichoabro** [comment]
nope

**Comment by BerkieBb** [comment]
Have you changed the fxmanifest.lua of qb-target?

**Comment by Kichoabro** [comment]
I fresh installed the new version without changing anything

**Comment by BerkieBb** [comment]
Oh yeah, I forgot, to run the raycast camera, you need to have opened the target atleast one time for it to set the right values and make the raycast work, it's hardcoded in it

**Comment by BerkieBb** [comment]
Try doing that and see if it works then

**Comment by Kichoabro** [comment]
Yeah, it works
